#ifndef PHYS_SETTINGS_H
#define PHYS_SETTINGS_H

#define PE_2D_PAIRS_INIT_LEN 1024
#define PE_MATS_INIT_LEN 16
#define PE_DEFAULT_AIR_RES 0.02f
#define PE_DEFAULT_RESTITUTION 0.85f
#define PE_DEFAULT_INERTIA 5.0f
#define PE_DEFAULT_INV_MASS 8192
#define PE_DEFAULT_POS { 0.0f, 0.0f }
#define PE_DEFAULT_SCALE { 16, 16 }
#define PE_DEFAULT_ROT 0
#define PE_DEFAULT_VEL { 0.0f, 0.0f }
#define PE_DEFAULT_ANG_VEL 0.0f
#define PE_INTERSECTION_MIN_OVERLAY 0.02f
#define PE_INTERSECTION_FIX_RATIO 0.045f
#define PE_GRID_GROUP_MAX_DEPTH 64
#define PE_GRID_GROUP_RB_LEN 64
#define PE_GRID_SIZE 256

#endif
